### ISSUE TITLE
IgnoreQueryFilters Method Not Supported

### ISSUE THREAD

**Issue by nootn** [aivascu/EntityFrameworkCore.AutoFixture#119]
I am using [Global Query Filters](https://docs.microsoft.com/en-us/ef/core/querying/filters) in EF Core 6.  When I have a query that uses the [IgnoreQueryFilters](https://docs.microsoft.com/en-us/dotnet/api/Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.IgnoreQueryFilters?view=efcore-6.0&viewFallbackFrom=net-6.0) extension method, the test breaks with an exception: 
```
System.NotSupportedException
Specified method is not supported.
   at Microsoft.EntityFrameworkCore.DbSet`1.System.Linq.IQueryable.get_Provider()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.IgnoreQueryFilters[TEntity](IQueryable`1 source)
```

Is that something that could be fixed in your library or should I try and add my own workaround for it?

**Comment by nootn** [comment]
I should have mentioned, I am using the "InMemoryCustomization" - I will do some more testing to make sure this is not something wrong with how I have configured things.

**Comment by nootn** [comment]
Oh, I just realised looking at NuGet, does this library rely on EF Core being < 5.  Is that something on your roadmap to make it work with later versions?

**Comment by aivascu** [comment]
@nootn only versions prior to .net 5 require ef core being < 5.0. Are you sure you're on the latest version?
https://www.nuget.org/packages/EntityFrameworkCore.AutoFixture/#dependencies-body-tab

**Comment by aivascu** [comment]
Closing due to inactivity. Feel free to reopen.
